### ISSUE TITLE
[zipModule] Improve error message if the zip command returns an error code

### ISSUE THREAD

**Issue by ygc2l** [PredictiveEcology/SpaDES.core#87] opened 2019-02-18 15:21 UTC
I suggest returning the code that the zip command returns if different from 0. Happens there: https://github.com/PredictiveEcology/SpaDES.core/blob/c0ace2e1365b9b62ad1738cff9d1a72745f4fc92/R/module-template.R#L968

I was getting the following warning down the track because the zip command was not found.

```
Warning message:
In file.remove(zipFileName) :
  cannot remove file 'fireSense_NWT_DataPrep_1.0.0.zip', reason 'No such file or directory'
```

**Comment by achubaty** [comment] 2019-11-21 15:12
is this still an issue?

**Comment by ygc2l** [comment] 2019-11-21 16:47
In short, yes

**Comment by achubaty** [comment] 2019-11-21 17:25
reprex?

**Comment by achubaty** [comment] 2019-11-21 17:28
also, i see this commit which sholud have dealt with the missing zip binary issue: https://github.com/PredictiveEcology/SpaDES.core/commit/520d4b4e0ea413f3bf856ba6085e6ab3ed4fa795

can you please confirm and provide a reprex?

**Comment by ygc2l** [comment] 2019-11-21 18:06
To reproduce:

```
newModule(name = "test", path = tempdir())
zipModule(name = "test", path = tempdir())
```

**Comment by achubaty** [comment] 2019-11-21 18:26
Because zip is properly installed, I can't reproduce on my machine.

1. confirm your `zip` installation (`Sys.getenv("R_ZIPCMD")` and `Sys.getenv("R_UNZIPCMD")`);
2. confirm you are using latest version of this package;
3. please post output from your machine so we have some clue as to why it's not working for you.

If this is idiosyncratic to your machine we will close the issue.

**Comment by ygc2l** [comment] 2019-11-21 18:38
I don't think we understand each other. I was simply suggesting to send an error message reporting that the `zip` command is not found. Because the following is not really informative

```
Warning message:
In file.remove(zipFileName) :
  cannot remove file 'fireSense_NWT_DataPrep_1.0.0.zip', reason 'No such file or directory'
```

Hoping that clarifies my request.

**Comment by achubaty** [comment] 2019-11-21 18:39
> also, i see this commit which sholud have dealt with the missing zip binary issue: [520d4b4](https://github.com/PredictiveEcology/SpaDES.core/commit/520d4b4e0ea413f3bf856ba6085e6ab3ed4fa795)

per above, this was added a while. please confirm that you are using the most recent GitHub version.

**Closed** 2019-11-21 20:54 UTC

**Comment by ygc2l** [comment] 2019-11-21 21:28
Is this issue solved?
