### ISSUE TITLE
loadSimList loads objects as lists

### ISSUE THREAD

**Issue by ianmseddy** [PredictiveEcology/SpaDES.core#167] opened 2021-06-14 20:35 UTC
Many of my simList objects load as lists when read with `loadSimList` . To my knowledge, the bug has occurred in `data.table` objects (e.g. `sim$cohortData`), model objects (e.g. `sim$modelBiomass`) and objects nested inside other lists (e.g. `sim$speciesGAMMs$Abie_las$gam`). It does not seem to occur with vectors (e.g. `sim$sppColorVect`, `sim$columnsForPixelGroups`). I have only had this issue working with the suggested workflow for `fireSense` in `SpaDES.project`.
So far it has occurred with many different simLists, on Windows and Linux OS and different machines, but not consistently. The workflow that triggers it is shown below
```
> ffSsimDataPrep
[1] "outputs/BC/fSsimDataPrep_BC.qs"

 saveSimList(
   sim = fSsimDataPrep,
   filename = ffSsimDataPrep,
   #filebackedDir = dfSsimDataPrep,
   fileBackend = 2
 )
  googledrive::drive_put(media = ffSsimDataPrep, path = gdriveURL, name = basename(ffSsimDataPrep), verbose = TRUE)
  #then later in a new session
  googledrive::drive_download(file = as_id(gdriveSims[["fSsimDataPrep"]]), path = ffSsimDataPrep)
  fSsimDataPrep <- loadSimList(ffSsimDataPrep)
  > class(fSsimDataPrep$cohortData2001)
[1] "list"
> as_id(gdriveSims[["fSsimDataPrep"]])
[1] "14lvEmS7d4oipgLeRIA4UIA1nj-1PMr0f"
attr(,"class")
[1] "drive_id"

```

**Comment by eliotmcintire** [comment] 2021-11-16 22:46
While the example I had to work with is now fixed with the PR above... I can't actually make a simple reprex that reproduces this:
```
library(SpaDES.core)
library(qs)
library(data.table)
dt <- data.table(a = 2, b = "dfsd")
sim <- simInit()
sim$dt <- copy(dt)
tf <- tempfile(); qsave(sim, file = tf)
sim2 <- qread(tf)
is(sim2$dt)
# [1] "data.table" "data.frame" "list"       "oldClass"   "vector"
```

**Comment by achubaty** [comment] 2022-01-19 16:29
can i close this for now?

while there are still some edge cases that aren't working, Eliot's previous commits dealt with many of the issues.

**Comment by ianmseddy** [comment] 2022-01-19 16:34
Sure, I think so. Just need to be aware of the edge cases. I believe this is lists of data.tables?

**Comment by eliotmcintire** [comment] 2022-01-19 17:13
I believe "lists of `data.table` objects" is still a problem. If we don't see it in our work, it is because we don't use, save and reload lists of `data.table` objects. I think the solution is to put in a check during `saveSimList`, possibly add an attribute to the list, then on `loadSimList` we can check for that attribute and rebuild the list of `data.table` objects. Of course the real correct solution is to come up with a reprex and send it to `qs` developers. I know it has been difficult to reproduce...

**Comment by achubaty** [comment] 2022-11-25 20:07
this is mostly resolved, but there may still be a few cases where it crops up:

- module metadata is incorrect (e.g., data.frame instead of data.table): solution is fix the metadata entry

**Closed** 2022-11-25 20:07 UTC
Labels: medium priority
